# Generated by Django 6.0.1 on 2026-03-10 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miPrimerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaquero',
            name='es_buscado',
            field=models.BooleanField(default=False),
        ),
    ]
