# Generated by Django 6.0.1 on 2026-03-10 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miPrimerApp', '0002_vaquero_es_buscado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaquero',
            name='sombrero',
        ),
    ]
